jenkins:
  systemMessage: "Welcome to your Jenkins instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
       - id: test
         password: test@123
  authorizationStrategy:
    projectMatrix:
      permissions:
        - "Overall/Administer:${JENKINS_ADMIN_ID}"
        - "Overall/Read:authenticated"
        - "Overall/Read:test"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: http://localhost:5000/
tool:
  JDK:
    installations:
      - name: JDK_master
        home: "/opt/java/openjdk"
  git:
    installations:
      - name: Default
        home: "git"
  Maven:
    installations:
      - name: mvn_master
        home: "/var/jenkins_home/maven"
jobs:
  - script: >
      job('Super-seed'){
        scm{
          git{
            remote{
              url('https://github.com/rahuldasdevops/microservice-pipelines.git')
              branch('develop@1.0')
            }
          }
        }
        steps{
          dsl{
            external('dsl/firstSpin.groovy')
          }
        }
      }
