FROM jenkins/jenkins:lts-jdk11
MAINTAINER Rahul Das
ENV JENKINS_SLAVE_AGENT_PORT=49100
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc.yaml
ENV HOME /var/jenkins_home
ENV NODEJS_HOME /opt/nodejs
ENV MAVEN_HOME $HOME/maven
ENV PATH $NODEJS_HOME/bin:$MAVEN_HOME/bin:$PATH
### Enable below PROXY if you run this in any enterprise
#ENV HTTPS_PROXY
#ENV HTTP_PROXY

COPY --chown=jenkins:jenkins plugins.txt /usr/share/jenkins/ref
RUN xargs /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

COPY --chown=jenkins:jenkins executors.groovy  /usr/share/jenkins/ref/init.groovy.d/executors.groovy
COPY --chown=jenkins:jenkins casc.yaml /var/jenkins_home/
#COPY --chown=jenkins:jenkins proxy.xml /var/jenkins_home/

ADD maven.tar.gz /usr/share/jenkins/ref/
USER root
ADD node-v14.18.0-linux-x64.tar.xz /opt/

RUN mv /usr/share/jenkins/ref/apache-maven-3.8.3 /usr/share/jenkins/ref/maven
RUN mv /opt/node-v14.18.0-linux-x64 /opt/nodejs
RUN chown -R jenkins:jenkins /opt/nodejs

USER jenkins
EXPOSE 8080
VOLUME jenkins_home
